=== MasterBluESkY/my-mdp/cfg/mdp.model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	xmlns:tns="https://github.com/willianconsta/my-mdp" 
	targetNamespace="https://github.com/willianconsta/my-mdp"
	elementFormDefault="qualified">
    <complexType name="mdp">
    	<all>
    		<element name="discountFactor">
    			<complexType>
    				<attribute name="value" type="double" use="required"/>
    			</complexType>
    		</element>
    		<element name="states">
    			<complexType>
    				<sequence>
    					<element name="state" type="tns:state" minOccurs="1" maxOccurs="unbounded" />
    				</sequence>
    			</complexType>
    		</element>
    		<element name="actions">
    			<complexType><sequence><element name="action" type="tns:action" minOccurs="1" maxOccurs="unbounded" /></sequence></complexType>
    		</element>
    		<element name="rewards">
    			<complexType><sequence><element name="reward" type="tns:reward" minOccurs="1" maxOccurs="unbounded" /></sequence></complexType>
    		</element>
    		<element name="transitions">
    			<complexType>
			    	<choice>
			    		<element name="transitionFromTo" maxOccurs="unbounded">
			    			<complexType>
					    		<attribute name="currentState" type="string" use="required"/>
					    		<attribute name="executing" type="string" use="required"/>
								<attribute name="nextState" type="string" use="required" />
								<attribute name="probability" type="double" use="required" />
			    			</complexType>
			    		</element>
			    	</choice>
			    </complexType>
    		</element>
    	</all>
    </complexType>

    <complexType name="state">
    	<attribute name="name" type="string" use="required"/>
    </complexType>
    <complexType name="action">
    	<attribute name="name" type="string" use="required"/>
    </complexType>
    <complexType name="reward">
    	<attribute name="state" type="string" use="required"/>
    	<attribute name="action" type="string" use="optional"/>
    	<attribute name="value" type="double" use="required" />
    </complexType>

	<!-- Root -->
    <element name="mdp" type="tns:mdp">
    	<key name="stateKey">
			<selector xpath="tns:states/tns:state" />
			<field xpath="@name" />
		</key>
		<key name="actionKey">
			<selector xpath="tns:actions/tns:action" />
			<field xpath="@name" />
		</key>
		<keyref name="rewardStateRef" refer="tns:stateKey">
    		<selector xpath="tns:rewards/tns:reward" />
    		<field xpath="@state" />
		</keyref>
		<keyref name="rewardActionRef" refer="tns:actionKey">
    		<selector xpath="tns:rewards/tns:reward" />
    		<field xpath="@action" />
		</keyref>
		<keyref name="transitionInitialStateRef" refer="tns:stateKey">
    		<selector xpath="tns:rewards/tns:reward" />
    		<field xpath="@state" />
		</keyref>
		<keyref name="transitionActionRef" refer="tns:actionKey">
    		<selector xpath="tns:rewards/tns:reward" />
    		<field xpath="@action" />
		</keyref>
    </element>
</schema>

=== MasterBluESkY/my-mdp/cfg/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<mdp xmlns="https://github.com/willianconsta/my-mdp"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://github.com/willianconsta/my-mdp ./mdp.model.xsd">
	<discountFactor value="0.9"/>
	<states>
		<state name="robot-at-x01y01" />
		<state name="robot-at-x01y02" />
		<state name="robot-at-x01y03" />
		<state name="robot-at-x02y01" />
		<state name="robot-at-x02y02" />
		<state name="robot-at-x02y03" />
		<state name="robot-at-x03y01" />
		<state name="robot-at-x03y02" />
		<state name="robot-at-x03y03" />
		<state name="robot-at-x04y01" />
		<state name="robot-at-x04y02" />
		<state name="robot-at-x04y03" />
		<state name="broken-robot" />
	</states>
	<actions>
		<action name="move-north" />
		<action name="move-south" />
		<action name="move-west" />
		<action name="move-east" />
	</actions>
	<rewards>
		<reward state="robot-at-x01y01" value="-1" />
		<reward state="robot-at-x01y02" value="-1" />
		<reward state="robot-at-x01y03" value="-1" />
		<reward state="robot-at-x02y01" value="-1" />
		<reward state="robot-at-x02y02" value="-1" />
		<reward state="robot-at-x02y03" value="-1" />
		<reward state="robot-at-x03y01" value="-1" />
		<reward state="robot-at-x03y02" value="-1" />
		<reward state="robot-at-x03y03" value="-1" />
		<reward state="robot-at-x04y01" value="-1" />
		<reward state="robot-at-x04y02" value="-1" />
		<reward state="robot-at-x04y03" value="0" />
		<reward state="broken-robot" value="-1" />
	</rewards>
	<transitions>
		<transitionFromTo currentState="robot-at-x01y01" executing="move-south" nextState="robot-at-x01y01" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x01y02" executing="move-south" nextState="robot-at-x01y01" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x01y03" executing="move-south" nextState="robot-at-x01y02" probability="0.900000" />
		<transitionFromTo currentState="robot-at-x01y03" executing="move-south" nextState="broken-robot" probability="0.100000" />
		<transitionFromTo currentState="robot-at-x02y01" executing="move-south" nextState="robot-at-x02y01" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x02y02" executing="move-south" nextState="robot-at-x02y01" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x02y03" executing="move-south" nextState="robot-at-x02y02" probability="0.63333333333" />
		<transitionFromTo currentState="robot-at-x02y03" executing="move-south" nextState="broken-robot" probability="0.36666666667" />
		<transitionFromTo currentState="robot-at-x03y01" executing="move-south" nextState="robot-at-x03y01" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x03y02" executing="move-south" nextState="robot-at-x03y01" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x03y03" executing="move-south" nextState="robot-at-x03y02" probability="0.36666666667" />
		<transitionFromTo currentState="robot-at-x03y03" executing="move-south" nextState="broken-robot" probability="0.63333333333" />
		<transitionFromTo currentState="robot-at-x04y01" executing="move-south" nextState="robot-at-x04y01" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x04y02" executing="move-south" nextState="robot-at-x04y01" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x04y03" executing="move-south" nextState="robot-at-x04y03" probability="1.000000" />
		<transitionFromTo currentState="broken-robot" executing="move-south" nextState="broken-robot" probability="1.000000" />
		
		<transitionFromTo currentState="robot-at-x01y03" executing="move-north" nextState="robot-at-x01y03" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x01y02" executing="move-north" nextState="robot-at-x01y03" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x01y01" executing="move-north" nextState="robot-at-x01y02" probability="0.900000" />
		<transitionFromTo currentState="robot-at-x01y01" executing="move-north" nextState="broken-robot" probability="0.100000" />
		<transitionFromTo currentState="robot-at-x02y03" executing="move-north" nextState="robot-at-x02y03" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x02y02" executing="move-north" nextState="robot-at-x02y03" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x02y01" executing="move-north" nextState="robot-at-x02y02" probability="0.63333333333" />
		<transitionFromTo currentState="robot-at-x02y01" executing="move-north" nextState="broken-robot" probability="0.36666666667" />
		<transitionFromTo currentState="robot-at-x03y03" executing="move-north" nextState="robot-at-x03y03" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x03y02" executing="move-north" nextState="robot-at-x03y03" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x03y01" executing="move-north" nextState="robot-at-x03y02" probability="0.36666666667" />
		<transitionFromTo currentState="robot-at-x03y01" executing="move-north" nextState="broken-robot" probability="0.63333333333" />
		<transitionFromTo currentState="robot-at-x04y03" executing="move-north" nextState="robot-at-x04y03" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x04y02" executing="move-north" nextState="robot-at-x04y03" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x04y01" executing="move-north" nextState="robot-at-x04y02" probability="0.100000" />
		<transitionFromTo currentState="robot-at-x04y01" executing="move-north" nextState="broken-robot" probability="0.900000" />
		<transitionFromTo currentState="broken-robot" executing="move-north" nextState="broken-robot" probability="1.000000" />
		
		<transitionFromTo currentState="robot-at-x01y01" executing="move-west" nextState="robot-at-x01y01" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x02y01" executing="move-west" nextState="robot-at-x01y01" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x03y01" executing="move-west" nextState="robot-at-x02y01" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x04y01" executing="move-west" nextState="robot-at-x03y01" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x01y02" executing="move-west" nextState="robot-at-x01y02" probability="0.900000" />
		<transitionFromTo currentState="robot-at-x01y02" executing="move-west" nextState="broken-robot" probability="0.100000" />
		<transitionFromTo currentState="robot-at-x02y02" executing="move-west" nextState="robot-at-x01y02" probability="0.900000" />
		<transitionFromTo currentState="robot-at-x02y02" executing="move-west" nextState="broken-robot" probability="0.100000" />
		<transitionFromTo currentState="robot-at-x03y02" executing="move-west" nextState="robot-at-x02y02" probability="0.63333333333" />
		<transitionFromTo currentState="robot-at-x03y02" executing="move-west" nextState="broken-robot" probability="0.36666666667" />
		<transitionFromTo currentState="robot-at-x04y02" executing="move-west" nextState="robot-at-x03y02" probability="0.36666666667" />
		<transitionFromTo currentState="robot-at-x04y02" executing="move-west" nextState="broken-robot" probability="0.63333333333" />
		<transitionFromTo currentState="robot-at-x01y03" executing="move-west" nextState="robot-at-x01y03" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x02y03" executing="move-west" nextState="robot-at-x01y03" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x03y03" executing="move-west" nextState="robot-at-x02y03" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x04y03" executing="move-west" nextState="robot-at-x04y03" probability="1.000000" />
		<transitionFromTo currentState="broken-robot" executing="move-west" nextState="broken-robot" probability="1.000000" />
		
		<transitionFromTo currentState="robot-at-x04y01" executing="move-east" nextState="robot-at-x04y01" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x01y01" executing="move-east" nextState="robot-at-x02y01" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x02y01" executing="move-east" nextState="robot-at-x03y01" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x03y01" executing="move-east" nextState="robot-at-x04y01" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x04y02" executing="move-east" nextState="robot-at-x04y02" probability="0.100000" />
		<transitionFromTo currentState="robot-at-x04y02" executing="move-east" nextState="broken-robot" probability="0.900000" />
		<transitionFromTo currentState="robot-at-x01y02" executing="move-east" nextState="robot-at-x02y02" probability="0.63333333333" />
		<transitionFromTo currentState="robot-at-x01y02" executing="move-east" nextState="broken-robot" probability="0.36666666667" />
		<transitionFromTo currentState="robot-at-x02y02" executing="move-east" nextState="robot-at-x03y02" probability="0.36666666667" />
		<transitionFromTo currentState="robot-at-x02y02" executing="move-east" nextState="broken-robot" probability="0.63333333333" />
		<transitionFromTo currentState="robot-at-x03y02" executing="move-east" nextState="robot-at-x04y02" probability="0.100000" />
		<transitionFromTo currentState="robot-at-x03y02" executing="move-east" nextState="broken-robot" probability="0.900000" />
		<transitionFromTo currentState="robot-at-x04y03" executing="move-east" nextState="robot-at-x04y03" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x01y03" executing="move-east" nextState="robot-at-x02y03" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x02y03" executing="move-east" nextState="robot-at-x03y03" probability="1.000000" />
		<transitionFromTo currentState="robot-at-x03y03" executing="move-east" nextState="robot-at-x04y03" probability="1.000000" />
